stages:
  - test
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

eslint:
  image: node:10.15
  stage: test
  cache:
    paths:
    - node_modules/
  script:
    - npm i
    - npm run audit
    - npm run lint
  tags:
    - docker
  only:
    - merge_requests


.deploy:
  stage: deploy
  variables:
    NODE_ENV: production
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$NODE_APP_INSTANCE --build-arg NODE_APP_INSTANCE=$NODE_APP_INSTANCE .
    - docker-compose -p 699-sdcoin up -d

deploy.develop:
  extends: .deploy
  environment:
    name: develop
    url:  https://699-sdcoin.pixelplex-test.by/
  variables:
    NODE_APP_INSTANCE: develop
  only:
    - develop
  tags:
    - pp-develop


firebase_deploy:
  stage: deploy
  artifacts:
      paths:
      - fastlane/logs
  script:
      - unlock_ci_keychain.sh
      - npm i cordova -g
      - npm i
      - npm run build
      - gem install bundler
      - bundle install --path vendor/bundle
      - echo $ANDROID_KEYSTORE_FILE | base64 --decode > keystore.jks
      - bundle exec fastlane ios firebase_deploy
      - bundle exec fastlane android firebase_deploy
  tags:
      - xcode
  only:
    - tags
  when: manual
